app:
  build: .
  ports:
    - "5000:5000"
  links:
    - redis
  volumes:
    - ".:/go/src/app"
  command: go run server.go
redis:
  image: redis
db:
  image: mysql:5.7
  volumes:
    - ./db/mysql_data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=app
